blacktop/ipsw

pkg/dyld/extract.go

When extracting a bunch of shared caches it quickly becomes confusing. This just appends the ipsw basename to the output file.

Append ipsw details to extracted shared cache file name.

---

Makefile

Switches to use the extracted cobra-cli command since it is being removed from the github.com/spf13/cobra module (xref https://github.com/spf13/cobra/issues/1597)

Switch to standalone cobra-cli dependency

---

Dockerfile
pkg/dyld/extract.go

I'm running on WSL2, and after installing `ipsw` with the deb file, I ran into some issues regarding `apfs-fuse` and output folders.
`apfs-fuse` requires root when using `/mnt` as the mount point. By creating a temporary directory in a location that the user likely owns, it is able to mount without root. Alternatively, creating a directory in `/tmp` could also work.
I also removed the prepending of `/data` when it is preparing the output directory. While this allows the output to be anywhere, it will break docker invocations that assumes the output path is in `/data`. Maybe we can specify in the docs, that for docker, the output paths must begin at `/data`, or maybe we can look for `/.dockerenv` and automatically prepend it.
Let me know what you think, thanks!

Fix permissions and mounts on WSL2/linux

---

Dockerfile

this patch adds `xz-utils` to the Docker container.
in my understanding, the `xz` binary should be the default for unpacking. currently, the docker container directly goes to the fall-back Go library `ulikunitz/xz`

Dockerfile: add xz-utils

---

cmd/ipsw/cmd/idev/idev_list.go
cmd/ipsw/cmd/macho/macho_dump.go

These two commands were missed in ae2a12f.

fix: move --color to global in `macho dump` and `idev list`

---

cmd/ipsw/cmd/download/download_ipsw.go

When downloading several IPSW files, the output directory structure was recursive, like so:
Now it looks like this:

fix: do not use recursive directories when downloading several IPSW

---

cmd/ipsw/cmd/macho/macho_dump.go

Allows --size and --count to override the size gathered from the segment
Example:
```
➜ ipsw macho dump launchd __TEXT.__config --bytes --size 142
• assuming given integer is in decimal
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

feat: Allow `macho dump` to get addr and size from segment

---

internal/utils/macos.go

On Intel Ventura 13.2, `GetKernelCollectionPath` attempts to return a kernel collection from `/System/Volumes/Preboot` (like on an Apple Silicon machine), because `sysctl -n bootobjectspath` does not throw an error.
If the machine is an `x86_64` machine, we should return `/System/Library/KernelCollections/BootKernelExtensions.kc`. Otherwise (if we are on an Apple Silicon device), defer to the previous behavior (try to return the kernelcache in `Preboot`, or return `/System/Library/KernelCollections/BootKernelExtensions.kc` if we cannot find the `Preboot` path with `sysctl`).
Desired behavior (`x86_64`, `22D49`):
```
• Parsing KernelManagement kernelcache
...
```
Observed behavior (`x86_64`, `22D49`):
```
⨯ file /System/Volumes/Preboot/.../com.apple.kernelcaches/kernelcache does not exist …
```

fix: return correct kernel collection path on x86_64 machines

---

internal/download/ota.go

I saw the following panic in our logs today:
```
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/blacktop/ipsw/internal/download.(*Ota).GetPallasOTAs(0xc000106820)
github.com/blacktop/ipsw/internal/download/ota.go:499 +0xe37
github.com/blacktop/ipsw/cmd/ipsw/cmd/download.glob..func9(0x204d820?, {0x4a14aa?, 0x4?, 0x4?})
github.com/blacktop/ipsw/cmd/ipsw/cmd/download/download_ota.go:271 +0x13df
github.com/spf13/cobra.(*Command).execute(0x204d820, {0xc0003ecec0, 0x4, 0x4})
github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x204a740)
github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.7.0/command.go:992 …
```

fix: guard the base64 repair/parse from invalid pallas response

---

Makefile

It's just a small typo. Better to be safe than sorry.

fix: `ARCH`, not `ARHC` in Makefile rules

---

cmd/ipsw/cmd/extract.go

For string value, GetBool returns false even the option is supplied, making this option unusable

bugfix: extract --dmg flag is not working

---

pkg/tbd/template.go

`ld` doesn't seem to recognize TBD files that don't end with `...`. This patch adds the missing three dots to the TBD template to avoid linking errors.
```console
% "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -dylib -arch x86_64 -platform_version macos 10.13.0 10.13.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -o /Users/user/Documents/MyTool/.build/x86_64-apple-macosx/debug/libMASDownloadMetadata.dylib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx …
```

fix: ld doesn't recognize tbd files that don't end with three dots

---

internal/commands/macho/objc.go

When some property or method references the type of its class, `ipsw` mistakenly generates an import directive for the header itself. This patch addresses the problem.
Before:
```objc
#include "NSOperation.h"
#include "ISOperation.h"
#include "ISOperationDelegate-Protocol.h"
#include "ISServiceProxy.h"
#include "ISStoreAccount.h"
#include "ISStoreClient.h"
#include "SSOperationProgress.h"
@interface ISOperation : NSOperation {
/* instance variables */
NSLock *_lock;
NSLock *_serviceProxyLock;
NSLock *_storeAccountLock;
}
@property (retain) NSRunLoop *operationRunLoop;
@property (retain) ISOperation *subOperation;
```
After:
```objc
#include "NSOperation.h"
#include "ISOperationDelegate-Protocol.h"
#include "ISServiceProxy.h"
#include "ISStoreAccount.h"
#include "ISStoreClient.h"
#include …
```

fix: avoid self import cycle

---

internal/commands/macho/objc.go

Only import header for superclass if it exists.
Before:
```objc
@import Foundation;
#include "NSWindowController.h"
#include "ISAuthenticationContext.h"
#include "ISDialog.h"
#include "ISStoreClient.h"
@class NSButton, NSImageView, NSProgressIndicator, NSTextField, NSWindow;
@interface ISSignInPrompt : NSWindowController {
```
After:
```objc
@import Foundation;
#include "ISAuthenticationContext.h"
#include "ISDialog.h"
#include "ISStoreClient.h"
@class NSButton, NSImageView, NSProgressIndicator, NSTextField, NSWindow, NSWindowController;
@interface ISSignInPrompt : NSWindowController {
```

fix: check if superclass has local header

---

internal/commands/macho/objc.go

Adds the necessary `#include` directives in protocol headers.
Before:
```objc
@import Foundation;
@protocol ISAccountService <ISServiceRemoteObject>
```
After:
```objc
@import Foundation;
#include "ISServiceRemoteObject-Protocol.h"
@protocol ISAccountService <ISServiceRemoteObject>
```
Closes #446

feat: generate imports for protocols

---

www/docs/guides/debugserver.md
www/docs/guides/download.md
www/docs/guides/shsh.md

Update (some) outdated commands and options in the documentation, as they've moved into a parent command or have been renamed
In summary
- `ipsw shsh` -> `ipsw ssh shsh`
- `ipsw debugserver` -> `ipsw ssh debugserver`
- `ipsw download ipsw`: `--show-latest` -> `--show-latest-version` and `--show-latest-build` (though, in context, the guides only mention how to see the latest iOS version, not build)

docs: Update outdated commands and options

---

www/docs/getting-started/installation.md

MacPorts hosts `ipsw` on their default repository now, so move new users over to their version. Other options remain available as `ipsw` on MacPorts may not always be up-to-date due to a review process required on each update.

docs: Update install instructions for MacPorts

---

internal/download/appstore.go

fix ipsw download ipa

---

cmd/ipsw/cmd/download/download.go
internal/download/itunes.go
internal/download/ota.go
pkg/usb/apps/installation.go

The intention here should be to initialize a slice with a capacity of length rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

cmd/ipsw/cmd/macho/macho_disass.go

When using `macho disass` command with new LLM features, like
```ipsw macho disass --dec --dec-model "GPT-4.1 (Preview)" --llm "copilot" --dec-lang "Swift" --demangle ./passd```
I've noticed that I've been asked to choose a model each time regardless of setting the `--dec-model` argument or not.
After taking a look inside, I've noticed that most of the keys in that module started with `macho.disass`, but the LLM-related keys started with `dyld.disass`, just like in `dyld_disass` module, which made me think that those keys should have been updated.
Doing that fixed the issue for me.

Fix llm-related key names for `macho disass`

---

cmd/ipsw/cmd/dyld/dyld_disass.go
internal/ai/ai.go
internal/ai/openrouter/openrouter.go
www/docs/guides/decompiler.md

This PR adds support for [openrouter.ai](https://openrouter.ai) LLM provider, which acts as a wrapper for many other models, which is useful, as one account can be used to try out many paid-for models without having to load up balance on each respective platform.
The implementation is basic, stuff like streaming is TODO.
I've added "Title" and "Referrer" headers to Openrouter requests so that it would be easier to track usage through their console, but if there are any project/privacy concerns, those can be removed.

feat: add `--llm openrouter` provider to `ipsw diass --dec` commands

---

internal/download/downloader.go

It looks like ipsw was getting stuck when calling `p.Wait()` because it was accidentally creating two separate progress bars, but only updating one of them.
Fixes #480

Fix resuming downloads getting stuck at completion by only creating one progress bar

---

cmd/ipsw/cmd/dyld/dyld_disass.go
cmd/ipsw/cmd/macho/macho_disass.go
internal/ai/ai.go
internal/commands/disass/disass.go
internal/utils/utils.go

This PR adds two new arguments to `dyld disass` and `macho disass`:
* `--dec-retries`, which allows configuring how many times to try calling the API again on failure (default 0 - no retries, behaves as before);
* `--dec-retry-backoff`, configures the amount of time to wait before querying the API again upon failure, which helps to avoid rate limit issues. Default value is 30 seconds.
Those parameters enable users to initiate a set-and-forget decompilation process for a big binary (while piping the output into a file, for instance).
On my set-up, I've been able to run the decompilation for two 3+ MB dylibs in a single run over the course of a day, with the retry logic saving me a couple of times in the process to continue after rate-limit errors from the API.

feat: add `--dec-retries` and `--dec-retry-backoff` arguments

---

internal/download/downloader.go

When downloading multiple files, the downloader will try to resume a non-existing file if it previously resumed another file that did exist. The reason for this is that the `resume` property did not get reset between downloads.
Example: 
1. ipsw wants to download 1.ipsw and 2.ipsw
2. 1.ipsw.download exists, ipsw resumes
3. 1.ipsw download completes
4. `resume` is now true
5. 2.ipsw.download does not exist, but `resume` remains true
6. Download fails with `failed to download IPSW: cannot open 2.ipsw.download: open 2.ipsw.download: no such file or directory`

Reset resume property on downloader before determining if file can and should be resumed
